# Generated by Django 3.2.9 on 2021-12-09 17:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('semestre', models.IntegerField(blank=True, null=True)),
                ('descricao', models.TextField()),
                ('creditos_aula', models.IntegerField(default=0)),
                ('creditos_trabalho', models.IntegerField(default=0)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('slug', models.SlugField(unique=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('nome', models.CharField(max_length=255)),
                ('data_de_nascimento', models.DateField()),
                ('file_path', models.CharField(max_length=255)),
                ('ano_de_ingresso', models.IntegerField()),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.departamento')),
                ('disciplina', models.ManyToManyField(to='app.Disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exlcuido', models.BooleanField()),
                ('conteudo', models.TextField()),
                ('data_de_criacao', models.DateTimeField(auto_now_add=True)),
                ('curtidas', models.IntegerField()),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('comentario_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.comentario')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_de_criacao', models.DateTimeField(auto_now_add=True)),
                ('nota_1', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0), django.core.validators.MaxValueValidator(limit_value=10)])),
                ('nota_2', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0), django.core.validators.MaxValueValidator(limit_value=10)])),
                ('nota_3', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0), django.core.validators.MaxValueValidator(limit_value=10)])),
                ('nota_4', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0), django.core.validators.MaxValueValidator(limit_value=10)])),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.disciplina')),
            ],
            options={
                'ordering': ['-data_de_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('slug', models.SlugField(unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('data_de_nascimento', models.DateField()),
                ('file_path', models.CharField(default='default.png', max_length=255)),
                ('ano_de_ingresso', models.IntegerField()),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.departamento')),
                ('disciplina', models.ManyToManyField(to='app.Disciplina')),
            ],
        ),
    ]
