# Generated by Django 3.2.9 on 2021-12-09 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211209_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dislike',
            old_name='users',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='users',
            new_name='autor',
        ),
    ]
