# Generated by Django 3.2.9 on 2021-12-08 00:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_aluno_disciplina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='nota_1',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0), django.core.validators.MaxValueValidator(limit_value=10)]),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='nota_2',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0), django.core.validators.MaxValueValidator(limit_value=10)]),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='nota_3',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0), django.core.validators.MaxValueValidator(limit_value=10)]),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='nota_4',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0), django.core.validators.MaxValueValidator(limit_value=10)]),
        ),
    ]
